/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}

import '@stencil/router';

import {
  MatchResults,
} from '@stencil/router';

declare global {

  namespace StencilComponents {
    interface AppHome {

    }
  }

  interface HTMLAppHomeElement extends StencilComponents.AppHome, HTMLStencilElement {}

  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };
  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement;
  }
  interface ElementTagNameMap {
    'app-home': HTMLAppHomeElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-home': JSXElements.AppHomeAttributes;
    }
  }
  namespace JSXElements {
    export interface AppHomeAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppProfile {
      'match': MatchResults;
    }
  }

  interface HTMLAppProfileElement extends StencilComponents.AppProfile, HTMLStencilElement {}

  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };
  interface HTMLElementTagNameMap {
    'app-profile': HTMLAppProfileElement;
  }
  interface ElementTagNameMap {
    'app-profile': HTMLAppProfileElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-profile': JSXElements.AppProfileAttributes;
    }
  }
  namespace JSXElements {
    export interface AppProfileAttributes extends HTMLAttributes {
      'match'?: MatchResults;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface HocTest {
      'messageData': any;
    }
  }

  interface HTMLHocTestElement extends StencilComponents.HocTest, HTMLStencilElement {}

  var HTMLHocTestElement: {
    prototype: HTMLHocTestElement;
    new (): HTMLHocTestElement;
  };
  interface HTMLElementTagNameMap {
    'hoc-test': HTMLHocTestElement;
  }
  interface ElementTagNameMap {
    'hoc-test': HTMLHocTestElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'hoc-test': JSXElements.HocTestAttributes;
    }
  }
  namespace JSXElements {
    export interface HocTestAttributes extends HTMLAttributes {
      'messageData'?: any;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface WithSubscription {
      'itemname': string;
      'stores': { [key: string]: any };
    }
  }

  interface HTMLWithSubscriptionElement extends StencilComponents.WithSubscription, HTMLStencilElement {}

  var HTMLWithSubscriptionElement: {
    prototype: HTMLWithSubscriptionElement;
    new (): HTMLWithSubscriptionElement;
  };
  interface HTMLElementTagNameMap {
    'with-subscription': HTMLWithSubscriptionElement;
  }
  interface ElementTagNameMap {
    'with-subscription': HTMLWithSubscriptionElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'with-subscription': JSXElements.WithSubscriptionAttributes;
    }
  }
  namespace JSXElements {
    export interface WithSubscriptionAttributes extends HTMLAttributes {
      'itemname'?: string;
      'stores'?: { [key: string]: any };
    }
  }
}


declare global {

  namespace StencilComponents {
    interface MyApp {

    }
  }

  interface HTMLMyAppElement extends StencilComponents.MyApp, HTMLStencilElement {}

  var HTMLMyAppElement: {
    prototype: HTMLMyAppElement;
    new (): HTMLMyAppElement;
  };
  interface HTMLElementTagNameMap {
    'my-app': HTMLMyAppElement;
  }
  interface ElementTagNameMap {
    'my-app': HTMLMyAppElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'my-app': JSXElements.MyAppAttributes;
    }
  }
  namespace JSXElements {
    export interface MyAppAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface RenderPropTest {
      'messageData': any;
    }
  }

  interface HTMLRenderPropTestElement extends StencilComponents.RenderPropTest, HTMLStencilElement {}

  var HTMLRenderPropTestElement: {
    prototype: HTMLRenderPropTestElement;
    new (): HTMLRenderPropTestElement;
  };
  interface HTMLElementTagNameMap {
    'render-prop-test': HTMLRenderPropTestElement;
  }
  interface ElementTagNameMap {
    'render-prop-test': HTMLRenderPropTestElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'render-prop-test': JSXElements.RenderPropTestAttributes;
    }
  }
  namespace JSXElements {
    export interface RenderPropTestAttributes extends HTMLAttributes {
      'messageData'?: any;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface RenderProp {
      'renderer': (props: { [key: string]: any }) => any;
      'stores': { [key: string]: any };
    }
  }

  interface HTMLRenderPropElement extends StencilComponents.RenderProp, HTMLStencilElement {}

  var HTMLRenderPropElement: {
    prototype: HTMLRenderPropElement;
    new (): HTMLRenderPropElement;
  };
  interface HTMLElementTagNameMap {
    'render-prop': HTMLRenderPropElement;
  }
  interface ElementTagNameMap {
    'render-prop': HTMLRenderPropElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'render-prop': JSXElements.RenderPropAttributes;
    }
  }
  namespace JSXElements {
    export interface RenderPropAttributes extends HTMLAttributes {
      'renderer'?: (props: { [key: string]: any }) => any;
      'stores'?: { [key: string]: any };
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
